- name: Main playbook
  hosts: all
  become: yes
  roles:
    - role: geerlingguy.pip

  tasks:
    - name: Install Docker on webservers
      become: yes
      apt:
        update_cache: yes
       
