- name: Main playbook
  hosts: all
  become: yes
  roles:
    - role: geerlingguy.pip
    
  tasks:
    - name: Install Docker on webservers
      hosts: webservers
      become: yes
      roles:
        - geerlingguy.docker
      tags:
        - install_docker
       
