- name: Main playbook
  hosts: all
  become: yes
  vars_files:
    - group_vars/webservers/vars.yml
    - group_vars/vault.yml
   
  roles:
    - role: geerlingguy.pip
  
  tasks:
  - name: Copy  file
    template:
      src:  ./templates/.env.j2
      dest: ~/.env
    tags:
    - deploy

  # TODO setto le variabili d'ambiente a partire dal file generato
  - name: Deploy Redmine
    community.docker.docker_container:
      name: hexlet-redmine
      image: redmine
      ports:
        - "{{ porthost }}:{{ portcontainer }}"
      env_file: "~/.env"
      detach: yes
    tags:
    - deploy

- hosts: webservers
  vars_files:
    - group_vars/webservers/vars.yml
    - group_vars/vault.yml
  tasks:
    - name: Import the Datadog Agent role from the Datadog collection
      import_role:
        name: datadog.datadog
  vars:
    datadog_api_key: "{{ datadog_api_key }}"



       
