- name: Main playbook
  hosts: all
  become: yes
  roles:
    - role: geerlingguy.pip
    - role: geerlingguy.docker

  #inserire task per la copia dei file dockercompose sulla macchina di destinazione

  tasks:
  #inserire task per la copia dei file dockercompose sulla macchina di destinazione
  - name: Deploy Redmine
  #modificar il comando per utilizzare un file docker compose
    ansible.builtin.command: docker run -d --name some-redmine redmine
    tags: 
      - deploy



       
