- name: Main playbook
  hosts: webservers
  become: yes
  roles:
    - role: geerlingguy.pip
  
  tasks:
  - name: Check if Docker is running
    command: docker info
    ignore_errors: true
    register: docker_info

  - name: Install Docker if not installed
    include_role:
      name: geerlingguy.docker
    when: docker_info.rc != 0

  - name: Ensure Docker is started
    service:
      name: docker
      state: started
    when: docker_info.rc == 0

  #TO-DO dichiarare le variabili per il template nel file "valut.yml"
  - name: Copy  file
    template:
      src:  ./templates/.env.j2
      dest: ~/.env
      tags:
      - deploy

  #Avvio il container redmine e inietto le variqabili d'ambiente sulla base dellevariabili criptate ne valut
  - name: Deploy Redmine
    community.docker.docker_container:
      name: hexlet-redmine
      image: redmine
      ports:
        - "80:3000"
      env_file: "~/.env"
      detach: yes
      tags:
      - deploy



       
