---
# tasks file for roles/redmine_deploy
- name: Deploy Redmine
  community.docker.docker_container:
    name: hexlet-redmine
    image: redmine
    ports:
      - "3000:3000"
    env_file: "~/.env"
    detach: yes